DROP DATABASE IF EXISTS GAMES_PLAYEDDB;

CREATE DATABASE GAMES_PLAYEDDB;

use GAMES_PLAYED;

CREATE TABLE GAMES_PLAYED (
    PRIMARY KEY (GAMES_PLAYED_ID)
    BEST_SCORE int NOT NULL AUTO_INCREMENT,
    WORST_SCORE int NOT NULL AUTO_INCREMENT, 
    GAMES_PLAYED int NOT NULL AUTO_INCREMENT, 
);

INSERT INTO GAMES_PLAYED (GAMES_PLAYED) VALUES (0);